### ISSUE TITLE
help on functions mismatches function availability

### ISSUE THREAD

**Issue by dicook** [njtierney/naniar#105]
According to the help where_na is available to use, but not when you try to use it:

> where_na(tao_shadow$sea_temp_c)
Error in where_na(tao_shadow$sea_temp_c) : 
  could not find function "where_na"

**Comment by njtierney** [comment]
Sure, it is `naniar:::where_na(airquality)` in the example docs, but it sounds like it might be useful to export - adding now

**Comment by njtierney** [comment]
``` r
library(naniar)

where_na(oceanbuoys) %>% head()
#>      row col
#> [1,] 463   4
#> [2,] 481   4
#> [3,] 637   4
#> [4,] 108   5
#> [5,] 109   5
#> [6,] 110   5
where_na(oceanbuoys$sea_temp_c)
#> [1] 463 481 637
```
