### ISSUE TITLE
Timeout during dplyr revdep check

### ISSUE THREAD

**Issue by krlmlr** [njtierney/naniar#107]
An attempt to `R CMD check` the naniar package with the current release candidate of dplyr (https://github.com/krlmlr/dplyr/tree/f-release) *and* with the current CRAN version didn't complete after two hours. The check stalled at `checking tests ...` .

I'm seeing similar symptoms with visdat, too.

This seems to be a local problem, because CRAN checks run just fine. What do I need to look at for troubleshooting this? Thanks.

CC @hadley.

**Comment by njtierney** [comment]
I'm closing this as things appear to be fine now - please feel to reopen if needed.
