### ISSUE TITLE
example data 

### ISSUE THREAD

**Issue by dicook** [njtierney/naniar#110]
Why do you have year, latitude and longitude of oceanbuoys set to be factors? That's not realistic. If you need them to be this for some of the functions, convert them to factors as necessary.

**Comment by njtierney** [comment]
Good point, I think that this was a hangup from the tao dataset from MissingDataGUI. 

I'll fix this in the next release.

**Comment by njtierney** [comment]
OK, fixed now - data was:

﻿``` r
naniar::oceanbuoys
#> # A tibble: 736 x 8
#>    year  latitude longitude sea_temp_c air_temp_c humidity wind_ew wind_ns
#>    <fct> <fct>    <fct>          <dbl>      <dbl>    <dbl>   <dbl>   <dbl>
#>  1 1997  0        -110            27.6       27.1     79.6   -6.40    5.40
#>  2 1997  0        -110            27.5       27.0     75.8   -5.30    5.30
#>  3 1997  0        -110            27.6       27.0     76.5   -5.10    4.50
#>  4 1997  0        -110            27.6       26.9     76.2   -4.90    2.50
#>  5 1997  0        -110            27.6       26.8     76.4   -3.50    4.10
#>  6 1997  0        -110            27.8       26.9     76.7   -4.40    1.60
#>  7 1997  0        -110            28.0       27.0     76.5   -2.00    3.50
#>  8 1997  0        -110            28.0       27.1     78.3   -3.70    4.50
#>  9 1997  0        -110            28.0       27.2     78.6   -4.20    5.00
#> 10 1997  0        -110            28.0       27.2     76.9   -3.60    3.50
#> # ... with 726 more rows
```

And now is:

``` r
naniar::oceanbuoys
#> # A tibble: 736 x 8
#>     year latitude longitude sea_temp_c air_temp_c humidity wind_ew wind_ns
#>    <dbl>    <dbl>     <dbl>      <dbl>      <dbl>    <dbl>   <dbl>   <dbl>
#>  1  1997        0      -110       27.6       27.1     79.6   -6.40    5.40
#>  2  1997        0      -110       27.5       27.0     75.8   -5.30    5.30
#>  3  1997        0      -110       27.6       27.0     76.5   -5.10    4.50
#>  4  1997        0      -110       27.6       26.9     76.2   -4.90    2.50
#>  5  1997        0      -110       27.6       26.8     76.4   -3.50    4.10
#>  6  1997        0      -110       27.8       26.9     76.7   -4.40    1.60
#>  7  1997        0      -110       28.0       27.0     76.5   -2.00    3.50
#>  8  1997        0      -110       28.0       27.1     78.3   -3.70    4.50
#>  9  1997        0      -110       28.0       27.2     78.6   -4.20    5.00
#> 10  1997        0      -110       28.0       27.2     76.9   -3.60    3.50
#> # ... with 726 more rows
```
