### ISSUE TITLE
add ORCID to DESCRIPTION

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#114]
For example: 

```
Title: Generalised Management Strategy Evaluation Simulator 
Description: Integrates game theory and ecological theory to construct social-ecological models that simulate the management of populations and stakeholder actions. These models build off of a previously developed management strategy evaluation (MSE) framework to simulate all aspects of management: population dynamics, manager observation of populations, manager decision making, and stakeholder responses to management decisions. The newly developed generalised management strategy evaluation (GMSE) framework uses genetic algorithms to mimic the decision-making process of managers and stakeholders under conditions of change, uncertainty, and conflict. Simulations can be run using gmse(), gmse_apply(), and gmse_gui() functions. 
Author: A. Bradley Duthie [aut, cre] (0000-0001-8343-4995), Nils Bunnefeld [ctb, fnd] (0000-0002-1349-4463), Jeremy Cusack [ctb] (0000-0003-3004-1586), Isabel Jones [ctb] (0000-0002-8361-1370), Erlend Nilsen [ctb] (0000-0002-5119-8331), Rocio Pozo [ctb] (0000-0002-7546-8076), Sarobidy Rakotonarivo [ctb] (0000-0002-8032-1431), Bram Van Moorter [ctb] (0000-0002-3196-1993) 
Maintainer: A. Bradley Duthie <brad.duthie@gmail.com> 
```

**Comment by njtierney** [comment]
Done for me, but I need @dicook 's ORCID, and also if @MilesMcBain or @ColinFay have one as well?

**Comment by dicook** [comment]
0000-0002-3813-7155

> On Dec 20, 2017, at 11:04 AM, Nicholas Tierney <notifications@github.com> wrote:
> 
> Done for me, but I need @dicook 's ORCID, and also if @MilesMcBain or @ColinFay have one as well?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

~*~*~*~
Professor Dianne Cook
Department of Econometrics and Business Statistics
E762A Menzies Building 
20 Chancellors Walk
Monash University
Clayton, VIC 3800
+61 (0)3 990 52608 (office)
+61 (0)4 312 71613 (mobile)
dicook@monash.edu
http://dicook.github.io
@visnut

**Comment by ColinFay** [comment]
Didn't have one before today, but here it is :) 
0000-0001-7343-1846

**Comment by njtierney** [comment]
OK great! added both of you in https://github.com/njtierney/naniar/commit/37ba9fa2c43a14e2e9b033b2014d04144b0d6858 - @MilesMcBain do you have one, minting a new one doesn't take too long :)
