### ISSUE TITLE
consider replace_na_with functions

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#129]
The creation of the `replace_with_na` functions has been nice - and the scoped variants (`_at`, `_if`, and `_all`) have been useful.

I think it would be useful to have functions that go the other way - from NA to a value.

This could be called `replace_na_with` - to provide a more direct complement to `replace_with_na`.

This is of interest to users, see [this SO question](https://stackoverflow.com/questions/8161836/how-do-i-replace-na-values-with-zeros-in-an-r-dataframe?rq=1)

This could be written something like this:

```r
replace_na_with <- function(vars, value) mutate_at(vars, funs(replace(., is.na(.), value)))
```

**Comment by HughParsonage** [comment]
Extant functions include `dplyr::coalesce` and `hutils::coalesce` (by me).

**Comment by njtierney** [comment]
We should re-export `coalesce` and provide documentation on how to use it, alongside the `replace_with_na` function
