### ISSUE TITLE
Document the datasets

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#15]
I'm not sure what the history is of these datasets are:
- brfss
- tao

I can probably remove `df`, as this was created from `wakefield`.

Read up on correctly documenting datasets: http://r-pkgs.had.co.nz/data.html

**Comment by dicook** [comment]
I can document the data sets. They both are in the missingDataGUI package

> On Aug 1, 2016, at 3:26 PM, Nicholas Tierney <notifications@github.com> wrote:
> 
> I'm not sure what the history is of these datasets are:
> 
> 	• brfss
> 	• tao
> I can probably remove df, as this was created from wakefield.
> 
> Read up on correctly documenting datasets: http://r-pkgs.had.co.nz/data.html
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by njtierney** [comment]
OK great, thank you Di!
