### ISSUE TITLE
replace_with_na throws error when replace list elements don't exist

### ISSUE THREAD

**Issue by m-sostero** [njtierney/naniar#160]
`replace_with_na` throws an error when *at least one* of the `replace` list elements doesn't exist in the data, even if other elements do exist.

```r
dat_ms <- tibble::tribble(
  ~x,  ~y,    ~z,
  1,   "A",   -100,
  3,   "N/A", -99,
  NA,  NA,    -98,
  -99, "E",   -101,
  -98, "F",   -1)

replace_with_na(
  dat_ms,
  replace = list(
    x = -99, # dat_ms$x exists
    w = -99  # dat_ms$w does not
  )
)
```

This gives
```r 
> Error in `[[<-.data.frame`(`*tmp*`, var, value = logical(0)) : 
  replacement has 0 rows, data has 5
```

I think the function return the data with all possible replacements, and throw an informative warning about replacement variables that do not exist in the data.

I will work on a PR for this.

**Comment by michael-dewar** [comment]
I don't know how to write a method, but an R wrapper like this should work:
```
safe_replace_with_na <- function(data, replace, ...){
	new_replace <- replace[names(replace) %in% names(data)]

	missing <- setdiff(names(replace), names(new_replace))
	if(length(missing) >0){
		warning(paste("Missing from data:", paste(missing, collapse = ", ")))
	}

	data %>% naniar::replace_with_na(new_replace, ...)
}
```

**Comment by njtierney** [comment]
Thanks for this, @michael-dewar! I've rolled this into `replace_with_na` and noted you in the NEWS file.
