### ISSUE TITLE
add .common_na_strings

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#168]
There are many other ways to represent missing values - I would like to include a bit of a mega string of values that naniar can search for, and also replace. This would cover things like:

- "N A "
- "NA "
- " NA"
- "N/A"
- "N / A"

etc.

**Comment by njtierney** [comment]
It would be ideal if this had some fancy regex I think.

**Comment by njtierney** [comment]
Current list of "NA' values

- "NA"
- "N A"
- "N/A"
- "NA "
- " NA"
- "N /A"
- "N / A"
- " N / A"
- "N / A "
- "na"
- "n a"
- "n/a"
- "na "
- " na"
- "n /a"
- "n / a"
- " a / a"
- "n / a "

**Comment by b-rodrigues** [comment]
Recently I've encountered "?".

**Comment by EdwinTh** [comment]
- "NULL"
- "null"
- "-999"
- "-"

**Comment by apear9** [comment]
"" is one i've encountered a few times when going from excel to R

**Comment by sinarueeger** [comment]
I'd add:
- "." (origin: data extracted from `STATA`)
- "-9" (when a variable is supposed to a range of values, e.g. `[0,1,2]`)

**Comment by cimentadaj** [comment]
Also "99"

Beware of the "66", "77" and "88" which are usualy things like "Didn't want to respond" or 'Question skipped'

**Comment by TonyLadson** [comment]
I've seen 'NR' and 'nr' for not read.

**Comment by njtierney** [comment]
Thank you everyone for your comments, really appreciate them!

I'm also linking in the twitter question which had some nice examples as well:

https://twitter.com/nj_tierney/status/1001340686409482240

**Comment by njtierney** [comment]
Thank you everyone for your comments! Here are `common_na_strings` and `common_na_numbers` in action:

``` r
library(naniar)

common_na_strings
#>  [1] "NA"     "N A"    "N/A"    "NA "    " NA"    "N /A"   "N / A" 
#>  [8] " N / A" "N / A " "na"     "n a"    "n/a"    "na "    " na"   
#> [15] "n /a"   "n / a"  " a / a" "n / a " "?"      "."      "NULL"  
#> [22] "null"   ""       "."
common_na_numbers
#> [1]    -9   -99  -999 -9999  9999    66    77    88

dat_ms <- tibble::tribble(~x,  ~y,    ~z,
                         1,   "A",   -100,
                         3,   "N/A", -99,
                         NA,  NA,    -98,
                         -99, "E",   -101,
                         -98, "F",   -1)

miss_scan_count(dat_ms, -99)
#> # A tibble: 3 x 2
#>   Variable     n
#>   <chr>    <int>
#> 1 x            1
#> 2 y            0
#> 3 z            1
miss_scan_count(dat_ms, c(-99,-98))
#> # A tibble: 3 x 2
#>   Variable     n
#>   <chr>    <int>
#> 1 x            2
#> 2 y            0
#> 3 z            2
miss_scan_count(dat_ms, c("-99","-98","N/A"))
#> # A tibble: 3 x 2
#>   Variable     n
#>   <chr>    <int>
#> 1 x            2
#> 2 y            1
#> 3 z            2
miss_scan_count(dat_ms, common_na_numbers)
#> # A tibble: 3 x 2
#>   Variable     n
#>   <chr>    <int>
#> 1 x            2
#> 2 y            0
#> 3 z            2
miss_scan_count(dat_ms, common_na_strings)
#> # A tibble: 3 x 2
#>   Variable     n
#>   <chr>    <int>
#> 1 x            4
#> 2 y            4
#> 3 z            5
```

Created on 2018-06-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by CMKnott** [comment]
Is it possible to add "#N/A" to common_na_strings ? 

(Sorry for the thread necromancy)

**Comment by njtierney** [comment]
done!

**Comment by njtierney** [comment]
Also, I appreciate the term, "thread necromancy", but thanks for your suggestion! :)

**Comment by CMKnott** [comment]
Legend 🥇

**Comment by aow27** [comment]
Hi, sorry to reopen this issue, but is `common_na_strings` behaving as you intended here? Because of the `""` and `.` within it, and the fact it is using regrex, it will match with any value that isn't `NA`. In the final example, you can see that column z is highlighted as all being NA strings, where I don't think it should be. Thanks.
