### ISSUE TITLE
Add the % missing on the bars of the lollypop plot generated by gg_miss_var()

### ISSUE THREAD

**Issue by AndreaPi** [njtierney/naniar#207]
Hi!

Thanks for the great package, my work EDAs are better because of `naniar` & `visdat`  :-D I like the lollypop plot generated by `gg_miss_var()` **a lot**, especially the faceting capability. However, I'd like to have the option to add the percentages on the lollypops. In other words, I'd like something like this:

``` r
library(naniar)
print(gg_miss_var(airquality, show_pct = TRUE))
```

![](https://i.imgur.com/P8aXM4U.png)

Created on 2018-08-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

But with the percentages added in correspondence of each bar.

**Comment by njtierney** [comment]
Hi @AndreaPi !

Glad to hear that you like visdat and naniar! :)

I really like this suggestion, but in terms of looking at the implementation, I think I might explore the idea of adding a custom geom/label, something like:

```r
library(naniar)
gg_miss_var(airquality) + geom_miss_label()
```

as I would like to avoid having too many arguments in one function.

I will explore this when I am looking at the next release of naniar, so unfortunately it might be a couple of months until I look at this again, but thank you for your suggestion!

**Comment by njtierney** [comment]
While I like this idea that I think that perhaps it is best left as a custom visualisation
