### ISSUE TITLE
seealso links broken

### ISSUE THREAD

**Issue by sfirke** [njtierney/naniar#228]
When in RStudio and I read `?replace_with_na` and try to click the functions linked under "See Also", I get the error message:

>Only help files, NEWS, DESCRIPTION and files under doc/ and demo/ in a package can be viewed

Lots of these links appear broken for me in other naniar function documentation, but not all of them.  For instance, When looking at `?add_any_miss` all of the See Also links work for me.

Maybe just something weird with my case but thought I'd check.  This is naniar v.0.4.1

**Comment by njtierney** [comment]
Thanks for this! I had done the following, which was broked:

```
@seealso [fun]()
```

instead of:

```
@seealso [fun()]
```

I will try and address this now

**Comment by njtierney** [comment]
Thanks for pointing that out, Sam! :)
