### ISSUE TITLE
 Why use !NA and NA instead of True or T and False?

### ISSUE THREAD

**Issue by ran88dom99** [njtierney/naniar#245]
naniar provides a data structure for working with missing data, the shadow matrix (Swayne and Buja, 1998). The shadow matrix is the same dimension as the data, and consists of binary indicators of missingness of data values, where missing is represented as “NA”, and not missing is represented as “!NA”, and variable names are kep the same, with the added suffix “_NA” to the variables.

Why use !NA and NA instead of True or T and False?

**Comment by njtierney** [comment]
Good question! It is because TRUE and FALSE can be confusing - are they referring to the data being missing, or present? This is one of the confusing things about `is.na` that I hoped to clarify
