### ISSUE TITLE
count/pct/prop of common missing values by row?

### ISSUE THREAD

**Issue by jzadra** [njtierney/naniar#248]
I have a data set that has both NA values and -99 values which mean something slightly different (NA = not seen, -99 = seen but unanswered questions on a survey).

I cannot find a function in `naniar` to do a count of -99 by row.  I see that there is `miss_scan_count` which allows for specifying what counts as a missing value, but this function operates on columns and gives totals by column.  Is there a similar function to do this by rows?  All the row-wise missing functions like pct/count/prop etc don't have an argument for what values count as missing, they only look for `NA`.

**Comment by njtierney** [comment]
#184 should resolve this - so I'll close this issue now, feel free to chime in there :)
