### ISSUE TITLE
Add `impute_zero()`

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#261]

**Comment by njtierney** [comment]
And maybe `impute_fixed` or something to allow for specified number to be imputed.

**Comment by caitlinhudon** [comment]
@njtierney Hey Nicholas! Is anyone working on this? I'm an open-source newbie but would love to take a whack at it if nobody else is.

**Comment by njtierney** [comment]
Hi @caitlinhudon !

My apologies for my delayed response, I've been on holiday and am only now coming back to tend to some of my projects.

I would very much welcome your input, let me know if I can help in the process. Happy to provide friendly feedback.

Cheers!
