### ISSUE TITLE
Feature suggestion: use tidyselect for replace_with_na_at()

### ISSUE THREAD

**Issue by jzadra** [njtierney/naniar#265]
I'd like to suggest implementing tidyselect for `replace_with_na_at()` to allow bare, unquoted variable names as well as the helpers `starts_with()`, `ends_with()`, and `contains()`.

I'd be happy to do a PR for this.

**Comment by njtierney** [comment]
Hi there!

Thanks!

Absolutely, I would welcome a PR for this, I've had this ticket open: https://github.com/njtierney/naniar/issues/125 for a while now 😅 and haven't gotten around to it, so please go ahead, I'm happy to code review.

I'm also wondering if maybe `across` and co (https://github.com/njtierney/naniar/issues/262) might even help abstract this issue away? What do you think?

**Comment by jzadra** [comment]
Yes good idea.  I haven't written anything using across yet, but I will look into it.

**Comment by njtierney** [comment]
I think this is superseded by #262
