### ISSUE TITLE
not missing package: there is no package called ‘visdat’

### ISSUE THREAD

**Issue by r0bis** [njtierney/naniar#280]
I am sorry, but this is an installation issue:

`install.packages("naniar")` gives the following error
```
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘visdat’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

But I have installed `visdat` and even loaded it with `library(visdat)`

**Comment by njtierney** [comment]
Hi there,

Thanks for posting - this is a bit of a tricky issue for me to replicate. Could you show me the output of `.libPaths()`?

Mine returns:

```
 .libPaths()
[1] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library"
```

Do you have any custom code in your .Rprofile that talks to / changes the libPaths library?

**Comment by njtierney** [comment]
Hi there, I wrote a bit about one of these issues with installation, hopefully that is helpful? https://www.njtierney.com/post/2020/05/29/there-is-no-pkg/

But for the moment I think that this is not an issue with naniar, I hope you have been able to resolve this :)
