### ISSUE TITLE
Error in mcar_test() : could not find function "mcar_test"

### ISSUE THREAD

**Issue by Bigsealion** [njtierney/naniar#281]
I have download 'naniar' package by `install.packages('naniar')`, and I want to using `mcar_test()`. but, I get following Error:
Error in mcar_test() : could not find function "mcar_test"
All the other functions are fine, and only `mcar_test` cannot be found.
Thank you for any reply!

**Comment by LukasWallrich** [comment]
This is not yet available in the CRAN version - to use it, you would need to install the development version from GitHub: `remotes::install_github("njtierney/naniar")`

**Comment by Bigsealion** [comment]
Thanks! It's very helpful!

**Comment by njtierney** [comment]
Thanks for chiming in @LukasWallrich  - sorry I missed this one. :)
