### ISSUE TITLE
mcar

### ISSUE THREAD

**Issue by benjaminwnelson** [njtierney/naniar#283]
Hello, I just updated naniar and it's saying that there is no function called "mcar_test". Any ideas on how to access this?

**Comment by sarahgspafford** [comment]
I am also encountering the same issue. Any help appreciated!

**Comment by njtierney** [comment]
Hi there,

I'm in the process of submitting naniar to CRAN, should be done by the end of this week - in the interim you can get `mcar_test` with:

```r
library(remotes)
install_github("njtierney/naniar")
```

**Comment by njtierney** [comment]
Let me know how you go and if you run into any issues :)

**Comment by sarahgspafford** [comment]
I was able to get it running again yesterday, thanks!

**Comment by benjaminwnelson** [comment]
That worked! Thank you!

**Comment by njtierney** [comment]
OK great! I'll close the issue now. Thanks for posting, glad to hear it is working for you!
