### ISSUE TITLE
Warning: guide = FALSE is deprecated | use guide = "none" instead

### ISSUE THREAD

**Issue by ddauber** [njtierney/naniar#288]
Hi there! 👋

---

Please see the warning issued below when running `gg_miss_var()`.

This warning does **NOT** show up with functions like: 

- `gg_miss_case`
- `gg_miss_var_cumsum()`
- `gg_miss_case_cumsum()`

(I have not tested all functions 😉)

It seems like an easy fix, though.

``` r
df <- dplyr::tribble(
  ~x, ~y,
  1,   1,
  2,  NA,
  NA,  3
  )

naniar::gg_miss_var(df)
#> Warning: It is deprecated to specify `guide = FALSE` to remove a guide. Please
#> use `guide = "none"` instead.
```

![](https://i.imgur.com/MHAuXgr.png)

**Comment by ddauber** [comment]
It seems this issue was resolved with [ede9539](https://github.com/njtierney/naniar/commit/ede9539b7e427bdee31b44c26f9a82851e0bb0a4). 👍

**Comment by njtierney** [comment]
Sorry I didn't get back to you - thanks for posting a great reprex! :)

**Comment by ddauber** [comment]
No problem at all. We are all busy people.👨‍💻
