### ISSUE TITLE
Changing UpSet plot's font size

### ISSUE THREAD

**Issue by lucazav** [njtierney/naniar#289]
I'm trying to change the size of the font used in the UpSet plot in the following way:

```
gg_miss_upset(tbl) + 
  theme(
    text = element_text(size=14)
  )
```

but I'm getting an empty plot.

Any hint about how to do that?

**Comment by njtierney** [comment]
Hi there!

Unfortunately the upset plot is not a regular ggplot object - it is built using https://github.com/hms-dbmi/UpSetR

In the future I might write my own version that is a regular ggplot object, but that is quite complex!

Some of the vignettes here might be able to help you out?

https://cran.rstudio.com/web/packages/UpSetR/

**Comment by lucazav** [comment]
I managed to do that with the following script:

`gg_miss_upset(tbl, text.scale = 2)`

Thanks!
