### ISSUE TITLE
what does naniar stand for?

### ISSUE THREAD

**Issue by anthoniraj** [njtierney/naniar#292]
can someone answer the full form of naniar?

**Comment by njtierney** [comment]
Good question!  

It is not an acronym, if that's what you mean? 

I've got a note on the name here: https://github.com/njtierney/naniar#a-note-on-the-name

Hope that answers your question! Happy missing data exploring.

**Comment by anthoniraj** [comment]
Thanks for your response. I understand that it is not an abbreviation but still the meaning is not clear. @MilesMcbain and @Hadley  can clarify with nanir meaning.
