### ISSUE TITLE
behaviour of is.na

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#31]
is.na will return true for `NA`

``` r
is.na(NA)
#> [1] TRUE

```

But for a quoted character, "NA", this is apparently not missing

```r
is.na("NA")
#> [1] FALSE
```

Somewhat suprisingly, `NaN` values are also regarded as missing values.

```r
is.na(NaN)
#> [1] TRUE

is.na("NaN")
#> [1] FALSE
```

I think that the quoted character "NA", "na", "Na", etc. should be regarded as missing, or there should be a specific function to coerce them to NAs. This function should also allow for some user specified NA characters. perhaps something like `coerce_na`

There might also be scope here for another NA function where people can specify different factors / structure for the NA values. For example, -99, -98, might be missing values, but could have specific reasons / mechanisms for being missing, and so should be recorded differently. This might be a function called `label_na`.

I'm not really sure if it is a problem that NaN values are considered missing. Perhaps it might be useful to provide some specific handlers for _na type objects, which also handle NaNs in a potentially more opinionated way.

**Comment by njtierney** [comment]
Also of interest is this behaviour, where `NaN`s are missings, but not when included with a character vector. This is because the coercion rules apply to `NaN`, and turn it into a character, which then gets ignored. Interesting to note.

``` r
n_miss(c(NaN))
#> [1] 1

n_miss(c(NaN, NaN))
#> [1] 2

n_miss(c(NaN, NaN, NA))
#> [1] 3

n_miss(c(NaN, NaN, NA, NA))
#> [1] 4

n_miss(c(NaN, NaN, NA, NA, 0))
#> [1] 4

c(NaN, NaN, NA, NA, 0)
#> [1] NaN NaN  NA  NA   0


n_miss(c(NaN, NaN, NA, NA, "p"))
#> [1] 2

c(NaN, NaN, NA, NA, "p")
#> [1] "NaN" "NaN" NA    NA    "p"
```

**Comment by njtierney** [comment]
Here's an interesting blog post on the behaviour of NA: https://www.r-bloggers.com/r-na-vs-null/

Also, here's a list of R functions / helpfiles to do with NAs

- [NA](https://stat.ethz.ch/R-manual/R-devel/library/base/html/NA.html)
- [addNA](https://stat.ethz.ch/R-manual/R-devel/library/base/html/factor.html)
- [datetimes](https://stat.ethz.ch/R-manual/R-devel/library/base/html/DateTimeClasses.html)
- [NaN](https://stat.ethz.ch/R-manual/R-devel/library/base/html/is.finite.html)
- [missing](https://stat.ethz.ch/R-manual/R-devel/library/base/html/missing.html) - used in functions, not strictly related, but worth reading.

**Comment by MilesMcBain** [comment]
See @jennbc's response to flother here: https://github.com/tidyverse/readr/issues/295

Maybe a warning is the best route if these string versions are encountered? I see this more as an issue on the data parsing side, it can be solved by specifying appropriate parsing options or post processing steps.

**Comment by MilesMcBain** [comment]
The `coerce_na` function sounds like it would be useful for post processing.

**Comment by njtierney** [comment]
Thanks for that @MilesMcBain that's a handy reference that I would have missed otherwise!

Perhaps I've misunderstood/missed something, but I was hoping that readr would have a function for this process of converting strings into NAs.

I'm not entirely sure what the process of `coerce_na` would look like. I was thinking something like  `dplyr::drop_na` - you might specify variables, and a grep/pattern to turn into vanilla NAs.

There's also an idea I was toying with of adding different levels/types of missings to indicate different mechanisms, but this would require a lot of thought, as NAs are _very carefully_ constructed in R. But on this topic, STATA has something like 28 different kinds of missing values. Might also be worthwhile looking into how SAS handles missings

**Comment by njtierney** [comment]
Also worth noting is `tidyr::replace_na`, this is very useful, but it currently takes a named list, which I think could be improved.

**Comment by njtierney** [comment]
This isn't really something to fix, more of a collection of some interesting notes, I've added this as sections of a book I'm (slowly) working on.
