### ISSUE TITLE
Time series: Proportion of missings in a given window

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#45]
The package imputeTS does a moving window plot of the missing values for a given moving window / break set.

``` r
# visualisation missing values for time series.
library(imputeTS)
# imputeTS

plotNA.distributionBar(tsNH4)
```

![](http://i.imgur.com/q91UMm1.png)

This is nice, if you know the right window size to look for, but I see at least three things that need to be implemented in naniar:

1. A function that creates a dataframe counting the number of missings for a given static window size
2. as for one, but allows you to specify windows of varying length (for example, what if you want to compare weekdays vs weekends, or something?
3. A plotting function or possibly a geom that takes a ts object and produces an equivalent plot to above

**Comment by njtierney** [comment]
Some progress has been made on item 1 and 3, with the functions, `miss_ts_summary` and `gg_miss_ts`, shown below:

``` r
library(narnia)
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats
library(imputeTS)

miss_ts_summary(data_ts = tsNH4,
                period = 100)
#> # A tibble: 46 x 5
#>    period_counter n_miss n_complete prop_miss prop_complete
#>             <int>  <int>      <int>     <dbl>         <dbl>
#>  1              1     12       4540      0.12          0.88
#>  2              2     37       4515      0.37          0.63
#>  3              3      8       4544      0.08          0.92
#>  4              4      7       4545      0.07          0.93
#>  5              5     12       4540      0.12          0.88
#>  6              6      0       4552      0.00          1.00
#>  7              7      1       4551      0.01          0.99
#>  8              8     30       4522      0.30          0.70
#>  9              9     66       4486      0.66          0.34
#> 10             10     41       4511      0.41          0.59
#> # ... with 36 more rows

gg_miss_ts(dat_ts = tsNH4,
           period = 100)
```

![](http://i.imgur.com/RQ47WkP.png)

Next tasks include extending this to work for:

- [ ] multiple time series objects `mts` (e.g., fpp2::arrivals)
- [ ] regular data.frames taht contain time series / date-time data
    - [ ] etiher detect a date/time object
    - [ ] user provides the date/time variable of interest
 
Also needed in this is to extend the periods so that they can be a vector

# n_period # how many periods in your time series do you want?
# size_period # how long are the periods in your time series.
# this could also be a vector
# size_period = c(3,10,100) OR
# size_period = c(100) OR
# size_period = c(100,50)

**Comment by MilesMcBain** [comment]
A nice accompnying plot to this for looking at structure might be an autocorrelation plot of prop missing.

**Comment by njtierney** [comment]
Autocorrelation would be interesting to investigate!

The period is the window size - so if `period = 100`, then each bar represents the proportion of missings and complete observations in that period - period 1 = 1-100, period 2 = 101-200, and so on.

**Comment by njtierney** [comment]
This has now changed to `miss_var_run` - we will be exploring using `.ts` or `.mts` objects in the future soon, but this is more general for any missings for a given variable in a dataset.

Below I demonstrate using the narnia pedestrian dataset, where we look at the number of missings in every 4000 rows.

``` r
library(narnia)
pedestrian %>%
  miss_var_span(var = hourly_counts,
                span_every = 4000)
#> # A tibble: 10 x 5
#>    span_counter n_miss n_complete prop_miss prop_complete
#>           <int>  <int>      <dbl>     <dbl>         <dbl>
#>  1            1      0       4000   0.00000       1.00000
#>  2            2      1       3999   0.00025       0.99975
#>  3            3    121       3879   0.03025       0.96975
#>  4            4    503       3497   0.12575       0.87425
#>  5            5    745       3255   0.18625       0.81375
#>  6            6      0       4000   0.00000       1.00000
#>  7            7      1       3999   0.00025       0.99975
#>  8            8      0       4000   0.00000       1.00000
#>  9            9    745       3255   0.18625       0.81375
#> 10           10    432       3568   0.10800       0.89200
```

The accompanying plot to this uses this function with a ggplot wrapper, currently still being developed.

**Comment by njtierney** [comment]
This has now been addressed with `miss_var_span` and `gg_miss_span`

```
library(naniar)

miss_var_span(data = pedestrian,
              var = hourly_counts,
              span_every = 1000) 
#> # A tibble: 38 x 5
#>    span_counter n_miss n_complete prop_miss prop_complete
#>           <int>  <int>      <dbl>     <dbl>         <dbl>
#>  1            1      0       1000     0.000         1.000
#>  2            2      0       1000     0.000         1.000
#>  3            3      0       1000     0.000         1.000
#>  4            4      0       1000     0.000         1.000
#>  5            5      0       1000     0.000         1.000
#>  6            6      0       1000     0.000         1.000
#>  7            7      1        999     0.001         0.999
#>  8            8      0       1000     0.000         1.000
#>  9            9      0       1000     0.000         1.000
#> 10           10      0       1000     0.000         1.000
#> # ... with 28 more rows

gg_miss_span(data = pedestrian,
             var = hourly_counts,
             span_every = 1000)
```

![](http://i.imgur.com/iJxFKoE.png)
