### ISSUE TITLE
Any thoughts on handling "censored" values

### ISSUE THREAD

**Issue by ldecicco-USGS** [njtierney/naniar#67]
The water-quality world has a lot of examples of data where a sample was measured, and the data was below a "detection limit". So, a numeric concentration cannot be given exactly, but something like "below 10 ug/L" or something. We've got packages/scripts floating around that deal with this type of data, but there might be a good home for it in Narnia....

I need to play around with this package, but I'm pretty excited to see it!

**Comment by njtierney** [comment]
Thanks for posting, @ldecicco-USGS! I haven't given censored values that much thought, outside of mentally noting that this would be an important area to think about carefully.

I would be interested to see these scripts, let me know if you would prefer to skype or email about that, if that would be easier :)

**Comment by njtierney** [comment]
Hiya @ldecicco-USGS ,

I've thought about this a bit now, and flagging a censored value should fall into a category of "special missing values", which will be created with [`recode_shadow` - this is currently in development in the "special-missing" branch](https://github.com/njtierney/naniar/blob/special-missing/R/shadow-recode.R#L177).

More on this soon, it will be in the V0.3.0 release, which should be happening soon.

After the V0.3.0 release, the V0.4.0 release will focus on tightening and speeding up the new features introduced.

**Comment by njtierney** [comment]
Just so the issues are linked - the related issue is #50

**Comment by njtierney** [comment]
closed by #202
