### ISSUE TITLE
Replacing selected values as NA

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#76]
Following on from excellent discussion with @ColinFay about replacing values with missing values.

Whilst there is a way to replace a value with an NA value in the tidyverse with `tidyr::replace_na()`:

```r
library(tidyverse)

dat_ms <- tibble::tribble(~x,  ~y,
                          1,   "A",
                          3,   "N/A",
                          NA,  NA,
                          -99, "E")
                          
dat_ms %>%
  replace_na(list(x = -99, y = c("N/A")))
```

There is currently not a convenient way to move in the opposite direction - replace certain values with NA.

One approach is to do something like this:

```
dat_ms %>% 
  mutate_all(.funs = function(x) replace(x, which(x == -99 | x == "N/A"), NA))
```

However, the user still needs to specify all possible missing values. Making the intention to replace for all to the user would be very useful. This function could be called `replace_with_na`, and would have similar behaviour to `replace_na`.

```
data %>% 
  replace_to_na(list(x = -99, "NAn", "Missing", "missing")) %>% 
  miss_var_summary()
```

This indicates to the user that you are replacing these missing values, then doing a summary on them.

To save the user from specifying all of the variable names to replace NA values, we can explore adding the additional suffixes, `_at`, `_if`, or `_all` - borrowing from the `scoped variants` of `summarise`, `mutate`, `transmute`, and `rename`, giving us:

* `replace_to_na_if`
* `replace_to_na_at`, and
*  `replace_to_na_all` 

These should then follow the same rules as the other scoped variants from dplyr, where:

> * _all affects every variable
> * _at affects variables selected with a character vector or vars()
> * _if affects variables selected with a predicate function

I think we are stretching this idea a bit, as what we are effectively writing is a customised `case_when` command. However, if this works out as I think it can, it would be quite powerful.

We can then take this idea further and extend it to shadow values, allowing us to specify directly the different flavours of missings, providing the verbs:

* `replace_shadow`
* `replace_shadow_all`
* `replace_shadow_if`
* `replace_shadow_at`

```
data %>%
  bind_shadow() %>%
  replace_shadow_all(-99, "NAn", "Missing", "missing")
```

This code would then only alter the shadow matrix, and leave the data intact as is, allowing us to leverage other features of the shadow matrix, and also possibly maybe add an additional factor level to it that describes the missingness mechanism (!NA, NA, NA_<reason1>, NA_<reason2>) - this has been described in the github issue <https://github.com/njtierney/narnia/issues/50> , but there needs to be a way to store the "codebook / data dictionary" of missingness mechanisms, so that the user has a way to look up / describe what a value like `NA_rainfall` really means. 

So I think that the idea of specifying these different missingness mechanisms still needs more work and experimentation. There are currently ways in haven to store the "different" values of missingness using `tagged_na()`, but I don't really like hiding important features from the user, and here I think that shadow matrix can be more practical.

We can then make the `miss_` functions have special behaviour for the `_NA` columns, so that gg_miss_var(data) could provide the summary of the number of pure NA values, and then also the number of values that are coded as NA_<reason_1>.

**Comment by njtierney** [comment]
Note that for the `replace_to_na` code, to add the scoped variants (`_at`, `_if`, and `_all`) - look into dplyr::recode and wrap this around `mutate_at`, `mutate_if`, and `mutate_all`)

**Comment by njtierney** [comment]
This should help make it possible to do things like `replace_to_na(x < 10)`

**Comment by njtierney** [comment]
Current behaviour of `replace_to_na`

``` r
library(naniar)

dat_ms <- tibble::tribble(~x,  ~y,    ~z,
                          1,   "A",   -100,
                          3,   "N/A", -99,
                          NA,  NA,    -98,
                          -99, "E",   -101,
                          -98, "F",   -1)

replace_to_na(dat_ms,
              to_na = list(x = -99))
#> # A tibble: 5 x 3
#>       x     y     z
#>   <dbl> <chr> <dbl>
#> 1     1     A  -100
#> 2     3   N/A   -99
#> 3    NA  <NA>   -98
#> 4    NA     E  -101
#> 5   -98     F    -1

replace_to_na(dat_ms,
              to_na = list(y = "N/A"))
#> # A tibble: 5 x 3
#>       x     y     z
#>   <dbl> <chr> <dbl>
#> 1     1     A  -100
#> 2     3  <NA>   -99
#> 3    NA  <NA>   -98
#> 4   -99     E  -101
#> 5   -98     F    -1
```

**Comment by njtierney** [comment]
Check out TJ Mahr's post: https://tjmahr.github.io/set-na-where-nonstandard-evaluation-use-case/

**Comment by njtierney** [comment]
And his awesome package [fillgaze](https://github.com/tjmahr/fillgaze)

**Comment by njtierney** [comment]
So, specifically we want:

- a function name that evokes the right feeling of converting values to NA
- a way of globally setting specific values to NA (such as "N/A" or "Not available")
- A way of setting specific variables values to NA (such as -99 in column Age only, so that we don't override Temperature values of -99 Celcius)

**Comment by ColinFay** [comment]
Just found out this function from {forcats}  : 

From the doc :

```
fct_explicit_na(f, na_level = "(Missing)")

f1 <- factor(c("a", "a", NA, NA, "a", "b", NA, "c", "a", "c", "b"))
table(f1)
f1
a b c 
4 2 2 

f2 <- fct_explicit_na(f1)
table(f2)
f2
        a         b         c (Missing) 
        4         2         2         3 
```

Works for factors though, maybe we can have a look and twist it to work with dataframe.

**Comment by ColinFay** [comment]
Hi @njtierney 
Here are some exploration about three functions : 
+ `replace_na_where` : takes the whole dataframe, and replace to NA everywhere the condition is met
+ `replace_na_at` : replace at specific columns 
+ `replace_na_if` : replace if the column meets the condition and where the value meets the second condition
```r
library(purrr)
library(tidyverse)
library(rlang)

small <- airquality %>% 
  slice(1:10)

create_mapper_na <- function(.p){
  glue::glue("~ {f_text(.p)} & !is.na(.x)") %>% 
    as.formula() %>%
    as_mapper()
}

na_set <- function(vec, .p) {
  modify_if(vec, create_mapper_na(.p) , ~ NA) %>% 
    reduce(c)
}

na_set(small$Ozone, ~ .x < 20)
 [1] 41 36 NA NA NA 28 23 NA NA NA

replace_na_where <- function(tbl, .p) {
  map_df(tbl, ~ na_set(.x, .p) )
} 

replace_na_where(small, ~ .x < 20)  
# A tibble: 10 x 6
   Ozone Solar.R  Wind  Temp Month   Day
   <int>   <int> <dbl> <int> <lgl> <lgl>
 1    41     190    NA    67    NA    NA
 2    36     118    NA    72    NA    NA
 3    NA     149    NA    74    NA    NA
 4    NA     313    NA    62    NA    NA
 5    NA      NA    NA    56    NA    NA
 6    28      NA    NA    66    NA    NA
 7    23     299    NA    65    NA    NA
 8    NA      99    NA    59    NA    NA
 9    NA      NA  20.1    61    NA    NA
10    NA     194    NA    69    NA    NA

replace_na_at <- function(tbl, .at, .p) {
  modify_at(tbl, .at, ~ na_set(.x, .p))
} 

replace_na_at(tbl = small, .at = c("Wind", "Ozone"), ~ .x < 20) 
# A tibble: 10 x 6
   Ozone Solar.R  Wind  Temp Month   Day
   <int>   <int> <dbl> <int> <int> <int>
 1    41     190    NA    67     5     1
 2    36     118    NA    72     5     2
 3    NA     149    NA    74     5     3
 4    NA     313    NA    62     5     4
 5    NA      NA    NA    56     5     5
 6    28      NA    NA    66     5     6
 7    23     299    NA    65     5     7
 8    NA      99    NA    59     5     8
 9    NA      19  20.1    61     5     9
10    NA     194    NA    69     5    10

replace_na_if <- function(tbl, .p, .pp) {
  modify_if(tbl, .p, ~ na_set(.x, .pp))
} 

small$Day <- as.factor(small$Day)

replace_na_if(tbl = small, is.numeric, ~ .x < 20) 

# A tibble: 10 x 6
   Ozone Solar.R  Wind  Temp Month    Day
   <int>   <int> <dbl> <int> <lgl> <fctr>
 1    41     190    NA    67    NA      1
 2    36     118    NA    72    NA      2
 3    NA     149    NA    74    NA      3
 4    NA     313    NA    62    NA      4
 5    NA      NA    NA    56    NA      5
 6    28      NA    NA    66    NA      6
 7    23     299    NA    65    NA      7
 8    NA      99    NA    59    NA      8
 9    NA      NA  20.1    61    NA      9
10    NA     194    NA    69    NA     10
```

Cool stuff is you can build complexe predicate for replacing to NA : 

```r
replace_na_where(small, ~ sqrt(.x) < 5)
# A tibble: 10 x 6
   Ozone Solar.R  Wind  Temp Month   Day
   <int>   <int> <lgl> <int> <lgl> <lgl>
 1    41     190    NA    67    NA    NA
 2    36     118    NA    72    NA    NA
 3    NA     149    NA    74    NA    NA
 4    NA     313    NA    62    NA    NA
 5    NA      NA    NA    56    NA    NA
 6    28      NA    NA    66    NA    NA
 7    NA     299    NA    65    NA    NA
 8    NA      99    NA    59    NA    NA
 9    NA      NA    NA    61    NA    NA
10    NA     194    NA    69    NA    NA
```

Is this what you're aiming for here? 
Anyway, these could be neat implementations :)

**Comment by njtierney** [comment]
Wow Colin! This is awesome!

I've got a couple of notes on the syntax about what I'd like, which is really really similar to what you've got there - so I think we're nearly there! But I just want to flesh this out and clear up in my head what I'm thinking first. I'll do my best to get back to you by Monday.

**Comment by njtierney** [comment]
I've had a first pass at this on https://github.com/njtierney/naniar/tree/scoped-replace-to-na, but there are a couple of implementation things that I would like to have, namely:

use of `vars()`
```r
replace_to_na_at(airquality, .at = vars(Wind, Ozone), ~ .x < 20)
```

How can we use `|` in this?
```r
# works with functions
replace_to_na_where(airquality, ~ sqrt(.x) < 5)

# not with two things
replace_to_na_where(airquality, ~ sqrt(.x) < 5 | .x < 5)
```

Additionally, it would be useful to conditionally set missings based on the conditions in another variable, which is what TJ Mahr's code does

For example:

```r
replace_to_na_where(airquality, Ozone = Solar.R < 130 & Wind > 7.4)
```

Additionally, I think I will change `.x` to be `.var` - to me `.var` gives the impression that we are working with one or more variables.

**Comment by njtierney** [comment]
Moved `replace_with_na_where` into branch [here](https://github.com/njtierney/naniar/tree/replace-with-na-where)
