### ISSUE TITLE
Investigate plotting for grouped missingness summaries

### ISSUE THREAD

**Issue by njtierney** [njtierney/naniar#86]
Once #39 is addressed and `group_by` works with the summaries, it should also then be possible to make relevant gg_miss_* plots that respect the grouping structure. 

I am unsure what this would look like at the moment, but it might either involve:

- another argument inside the `gg_miss_*` plots

```r
gg_miss_var(airquality, group = Month)
```

or maybe

- additional function with a suffix

```r
gg_miss_var_by(airquality, Month)
```

I think I prefer the former option.

**Comment by njtierney** [comment]
I have added a `group` argument to `gg_miss_var`, `gg_miss_case`, and `gg_miss_span` in branch [gg-miss-groups](https://github.com/njtierney/naniar/tree/gg-miss-groups)

This makes it easier for users to visualise these plots across the values of another variable. In the future I will consider adding `group` to the other shorthand plotting function, but at the moment these seemed to be the ones that would benefit the most from this feature.

Example output below

``` r
library(naniar)

# gg_miss_var 
gg_miss_var(airquality)
```

![](https://i.imgur.com/ZXxWjFK.png)

``` r

gg_miss_var(airquality, 
            group = Month)
```

![](https://i.imgur.com/NVaLTJK.png)

``` r

# gg_miss_case

gg_miss_case(airquality)
```

![](https://i.imgur.com/8AhxVCO.png)

``` r
gg_miss_case(airquality, order_cases = TRUE)
```

![](https://i.imgur.com/ePYvot7.png)

``` r

gg_miss_case(airquality, group = Month)
```

![](https://i.imgur.com/noYIQPi.png)

``` r

# gg_miss_span

gg_miss_span(pedestrian, hourly_counts, span_every = 3000)
```

![](https://i.imgur.com/2jYoF2X.png)

``` r
gg_miss_span(pedestrian, hourly_counts, span_every = 3000, group = sensor_name)
```

![](https://i.imgur.com/CClmKwF.png)

**Comment by njtierney** [comment]
@earowang what do you think about the `group` argument?

Another syntax I was thinking might be nice is `facet_by`

```r
gg_miss_span(pedestrian, hourly_counts, span_every = 3000, group = sensor_name)
gg_miss_span(pedestrian, hourly_counts, span_every = 3000, facet_by = sensor_name)

gg_miss_case(airquality, group = Month)
gg_miss_case(airquality, facet_by = Month)
```

What do you think?

**Comment by earowang** [comment]
I would suggest using `facet` instead of `facet_by` as the argument name. Currently, the `geom_*` functions uses the arg `group` to do data grouping b/f drawing the plot. But in the `gg_miss_*`, it would overwrite the `group` in `geom_*`  if using `group`. And `facet` gives a clearer message that a faceted plot is generated.

**Comment by njtierney** [comment]
Yup, that makes sense! Thanks for the input @earowang ! :)
